---

- name: disable ssh remote root login
  lineinfile:
    dest: "{{ ssh_sshd_config }}"
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify:
    - restart sshd

- name: enable ssh strict mode
  lineinfile:
    dest: "{{ ssh_sshd_config }}"
    regexp: "^#?StrictModes"
    line: "StrictModes yes"
    state: present
  notify:
    - restart sshd
