---

- name: github-cli - Adding keyring
  become: yes
  ansible.builtin.shell: |
    sudo rm /usr/share/keyrings/{{gpg_info.name}}-archive-keyring.gpg
    curl -fsSL {{gpg_info.url}} | sudo gpg --dearmor -o /usr/share/keyrings/{{gpg_info.name}}-archive-keyring.gpg
  with_items:
    - { url: 'https://cli.github.com/packages/githubcli-archive-keyring.gpg', name: 'githubcli' }
    - { url: 'https://apt.releases.hashicorp.com/gpg', name: 'terraform' }
  loop_control:
    loop_var: gpg_info


- name: github-cli - Adding Sources.list
  become: yes
  ansible.builtin.lineinfile:
    line: "deb [arch=amd64 signed-by=/usr/share/keyrings/{{repo_info.name}}-archive-keyring.gpg] {{repo_info.url}}"
    state: present
    create: yes
    path: /etc/apt/sources.list.d/{{repo_info.name}}.list
  with_items:
    - { url: 'https://cli.github.com/packages stable main', name: 'githubcli' }
    - { url: 'https://apt.releases.hashicorp.com {{ansible_distribution_release}} main', name: 'terraform' }
  loop_control:
    loop_var: repo_info

- name: diff-so-fancy - Adding PPA
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:aos1/diff-so-fancy

- name: lazygit (depr)
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:lazygit-team/release
