- name: Setup OS specific system config
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Create ~/bin Directory
  ansible.builtin.file:
    path: ~/bin
    state: directory
    mode: '0755'

- name: Copy over the scripts into ~/bin
  ansible.builtin.copy:
    src: bin/{{ item }}
    dest: ~/bin/
    mode: '0755'
  with_items:
    - lns
    - prettyping

