---
- name: debug
  debug:
    var: ansible_distribution

- name: debug
  debug:
    var: ansible_distribution

- name: Setup OS specific repositories/taps 
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Get OS specific Package names
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: Install Common Packages
  become: yes
  ansible.builtin.package:
    state: present
    name: "{{common_packages_list}}"

- name: Install Packages with Different Names across Platforms
  become: yes
  ansible.builtin.package:
    state: present
    name:
      - '{{fd_find}}'
      - '{{github_cli}}'
      - '{{the_silver_searcher}}'
