---
- name: Base Setup
  hosts: all
  roles:
    - role: common 
      tags: 
        - role-common
    - role: install-packages
      tags:
        - role-install-packages
    - role: os-config
      tags:
        - role-os-config
